fortune:
  fortuneServiceURL: http://fortune-teller-fortune-service.apps.internal

spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    discovery:
      enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false

hystrix:
  stream:
    queue:
      enabled: false
